"""
data_utils.py
Data loading utilities for TPU self-play datasets.
Uses PyTorch DataLoader for efficient CPU-side prefetching.
"""
import os
import sys
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from typing import Tuple
from glob import glob

# On Windows, multiprocessing can cause issues; fallback to file-system sharing.
if sys.platform == 'win32':
    try:
        torch.multiprocessing.set_sharing_strategy('file_system')
    except:
        pass


class TPUSelfPlayDataset(Dataset):
    """
    Dataset for self-play data generated by tpu_selfplay.py.
    Expects .npz files with keys: obs, policy, value, mask.
    Loads all data into memory (concatenated) for fast access.
    """
    def __init__(self, data_dir: str):
        self.data_dir = data_dir

        obs_list = []
        policy_list = []
        value_list = []

        npz_files = sorted(glob(os.path.join(data_dir, "*.npz")))
        print(f"[Dataset] Loading data, found {len(npz_files)} files...")

        for npz_file in npz_files:
            try:
                data = np.load(npz_file)
                obs = data["obs"]  # (T, B, 19, 19, 17)
                policy = data["policy"]  # (T, B, 362)
                value = data["value"]   # (T, B)
                mask = data["mask"]  # (T, B)
                
                T, B = obs.shape[:2]

                # Flatten time and batch dimensions
                obs_flat = obs.reshape(T * B, 19, 19, 17)
                policy_flat = policy.reshape(T * B, 362)
                value_flat = value.reshape(T * B)
                mask_flat = mask.reshape(T * B)

                # Keep only valid moves (where mask is True)
                valid_indices = np.where(mask_flat)[0]

                obs_list.append(obs_flat[valid_indices])
                policy_list.append(policy_flat[valid_indices])
                value_list.append(value_flat[valid_indices])
            except Exception as e:
                print(f"Error reading {npz_file}: {e}")

        if obs_list:
            self.obs = np.concatenate(obs_list, axis=0)
            self.policy = np.concatenate(policy_list, axis=0)
            self.value = np.concatenate(value_list, axis=0)
            print(f"[Dataset] Loaded {len(self.obs)} samples.")
        else:
            self.obs = np.array([])
            self.policy = np.array([])
            self.value = np.array([])
            print("[Dataset] Warning: no data found.")

    def __len__(self) -> int:
        return len(self.obs)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Returns a single sample as PyTorch tensors (float32 for obs and policy, int32 for value?).
        The DataLoader will batch them; in the training loop, convert to jnp.array.
        """
        return (
            torch.tensor(self.obs[idx], dtype=torch.float32),
            torch.tensor(self.policy[idx], dtype=torch.float32),
            torch.tensor(self.value[idx], dtype=torch.float32)
        )


def create_dataloader(dataset: Dataset, batch_size: int, shuffle: bool = True,
                      num_workers: int = 4, pin_memory: bool = True) -> DataLoader:
    """
    Creates a DataLoader for TPU training.
    On Windows, multiprocessing is disabled (num_workers=0) due to potential issues.
    drop_last=True ensures all batches have the same size, important for pmap.
    """
    if sys.platform == 'win32':
        num_workers = 0  

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=pin_memory if num_workers > 0 else False,
        drop_last=True  
    )
